@startuml

class User {
    .. Attributes ..
    -{static} MIN_NAME_LENGTH : final int
    -{static} MAX_NAME_LENGTH : final int
    -{static} MAX_EMAIL_LENGTH : final int 
    -{static} MIN_ADDRESS_LENGTH : final int
    -{static} MAX_ADDRESS_LENGTH : final int
    -{static} MIN_HEART_RATE : final int
    -{static} MAX_HEART_RATE : final int
    -{static} MIN_WEIGHT : final int
    -{static} MAX_WEIGHT : final int
    -{static} MIN_HEIGHT : final int
    -{static} MAX_HEIGHT : final int
    -id : int
    -name : String
    -email : String
    -address : String
    -heartRate : int
    -weight : int
    -height : int
    -type : User.Type
    -activities : ArrayList<Activity>
    -registers : HashMap<LocalDateTime, Register>
    -plan : Plan
    --
    .. Constructors ..
    +User()
    +User(int id, String name, String email,
        String address, int heartRate, int weight,
        int height, Type type)
    +User(int id, String name, String email,
        String address, int heartRate, int weight, int height,
        Type type, ArrayList<Activity> activities,
        HashMap<LocalDateTime, Register> registers, Plan plan)
    +User(User user)
    .. Methods - Getters ..
    +getId() : int
    +getName() : String
    +getEmail() : String
    +getAddress() : String
    +getHeartRate() : int
    +getWeight() : int
    +getHeight() : int
    +getType() : User.Type
    +getActivities() : ArrayList<Activity>
    +getRegisters() : HashMap<LocalDateTime, Register>
    +getPlan() : Plan
    .. Methods - Setters ..
    +setId(int id) : void
    +setName(String name) : void
    +setEmail(String email) : void
    +setAddress(String address) : void
    +setHeartRate(int heartRate) : void
    +setWeight(int weight) : void
    +setHeight(int height) : void
    +setType(Type type) : void
    +setActivities(ArrayList<Activity> activities) : void
    +setRegisters(HashMap<LocalDateTime, Register> registers) : void
    +setPlan(Plan plan) : void
    .. Methods - Other ..
    +toString() : String
    +equals(Object o) : boolean
    +clone() : User
    .. Methods - Manage Users ..
    +enterName(Scanner sc) : String
    +enterEmail(Scanner sc, HashMap<Integer, User> users) : String
    +enterAddress(Scanner sc) : String
    +enterHeartRate(Scanner sc) : int
    +enterWeight(Scanner sc) : int
    +enterHeight(Scanner sc) : int
    +enterType(Scanner sc) : User.Type
    +{static} create(Scanner sc, HashMap<Integer, User> users, User user) : User
    +{static} search(Scanner sc, HashMap<Integer, User> users, User user) : User
    +{static} view(Scanner sc, HashMap<Integer, User> users, User user) : void
    +{static} delete(Scanner sc, HashMap<Integer, User> users, User user) : void
    .. Methods - Activities ..
    +addActivity(Activity activity) : void
    +deleteActivity(Activity activity) : void
    .. Methods - Registers ..
    +register(LocalDateTime date, Activity register) : void
    +viewRegisters() : void
}

enum User.Type {
    OCCASIONAL(40),
    AMATEUR(60),
    PROFESSIONAL(90)
    --
    .. Attribute ..
    -nutritionMultiplier : int
    .. Getter ..
    +getNutritionMultiplier() : int
}

abstract class Activity {
    .. Attributes ..
    #name : String
    #duration : int
    #intensity : int
    #hard : boolean
    #calories : int
    --
    .. Constructors ..
    +Activity()
    +Activity(String name, int duration, int intensity, boolean hard, int calories)
    +Activity(Activity activity)
    .. Methods - Getters ..
    +{abstract} getACTIVITY_TYPE() : int
    +getName() : String
    +getDuration() : int
    +getIntensity() : int
    +getHard() : boolean
    +getCalories() : int
    .. Methods - Setters ..
    +setName(String name) : void
    +setDuration(int duration) : void
    +setIntensity(int intensity) : void
    +setHard(boolean hard) : void
    +setCalories(int calories) : void
    .. Methods - Others ..
    +{abstract} toString() : String
    +{abstract} equals(Object o) : boolean
    +{abstract} clone() : Activity
    +{abstract} caloriesBurned(User u) : int
    .. Methods - Activity Type ..
    +isDistance() : boolean
    +isDistanceAltimetry() : boolean
    +isRepetition() : boolean
    +isRepetitionWeight() : boolean
    +getType() : int
    +getTypeString() : String
    .. Methods - Manage Activities ..
    +{abstract} create(Scanner sc, ArrayList<Activity> userActivities) : Activity
    +{static} createAux(Scanner sc, ArrayList<Activity> userActivities, int activityType) : Activity
    +{static} createMenu(Scanner sc, ArrayList<Activity> userActivities) : Activity
    +{static} search(Scanner sc, ArrayList<Activity> userActivities) : Activity
    +{static} register(Scanner sc, User u) : User
}

package activities {
    class Distance extends Activity {
        .. Attributes ..
        -{static} final ACTIVITY_TYPE : int
        -{static} final MET_VALUE : double
        -distance : int
        --
        .. Constructors ..
        +Distance()
        +Distance(String name, int duration, int intensity,
            boolean hard, int calories)
        +Distance(String name, int duration, int intensity,
            boolean hard, int calories, int distance)
        +Distance(Distance distance)
        .. Methods - Getters ..
        +getACTIVITY_TYPE() : final int
        +getDistance() : int
        .. Methods - Setters ..
        +setDistance(int distance) : void
        .. Methods - Others ..
        +toString() : String
        +equals(Object o) : boolean
        +clone() : Distance
        +calculateCalories(User u) : int
        +create(Scanner sc, ArrayList<Activity> userActivities) : Activity
    }

    class DistanceAltimetry extends Activity {
        .. Attributes ..
        -{static} final ACTIVITY_TYPE : int
        -{static} final MET_VALUE : double
        -{static} final ALTIMETRY_FACTOR : int
        -distance : int
        -altimetry : int
        --
        .. Constructors ..
        +DistanceAltimetry()
        +DistanceAltimetry(String name, int duration, int intensity, boolean hard, int calories)
        +DistanceAltimetry(String name, int duration, int intensity, boolean hard, int calories,
            int distance, int altimetry)
        +DistanceAltimetry(DistanceAltimetry distanceAltimetry)
        .. Methods - Getters ..
        +getACTIVITY_TYPE() : final int
        +getDistance() : int
        +getAltimetry() : int
        .. Methods - Setters ..
        +setDistance(int distance) : void
        +setAltimetry(int altimetry) : void
        .. Methods - Others ..
        +toString() : String
        +equals(Object o) : boolean
        +clone() : DistanceAltimetry
        +calculateCalories(User u) : int
        +create(Scanner sc, ArrayList<Activity> userActivities) : Activity
    }

    class Repetition extends Activity {
        .. Attributes ..
        -{static} final ACTIVITY_TYPE : int
        -{static} final MET_VALUE : double
        -repetition : int
        --
        .. Constructors ..
        +Repetition()
        +Repetition(String name, int duration, int intensity, boolean hard, int calories)
        +Repetition(String name, int duration, int intensity, boolean hard, int calories,
            int repetition)
        +Repetition(Repetition repetition)
        .. Methods - Getters ..
        +getACTIVITY_TYPE() : final int
        +getRepetition() : int
        .. Methods - Setters ..
        +setRepetition(int repetition) : void
        .. Methods - Others ..
        +toString() : String
        +equals(Object o) : boolean
        +clone() : Repetition
        +calculateCalories(User u) : int
        +create(Scanner sc, ArrayList<Activity> userActivities) : Activity
    }

    class RepetitionWeight extends Activity {
        .. Attributes ..
        -{static} final ACTIVITY_TYPE : int
        -{static} final MET_VALUE : double
        -repetition : int
        -weight : int
        --
        .. Constructors ..
        +RepetitionWeight()
        +RepetitionWeight(String name, int duration, int intensity, boolean hard, int calories)
        +RepetitionWeight(String name, int duration, int intensity, boolean hard, int calories,
            int repetition, int weight)
        +RepetitionWeight(RepetitionWeight repetitionWeight)
        .. Methods - Getters ..
        +getACTIVITY_TYPE() : final int
        +getRepetition() : int
        +getWeight() : int
        .. Methods - Setters ..
        +setRepetition(int repetition) : void
        +setWeight(int weight) : void
        .. Methods - Others ..
        +toString() : String
        +equals(Object o) : boolean
        +clone() : RepetitionWeight
        +calculateCalories(User u) : int
        +create(Scanner sc, ArrayList<Activity> userActivities) : Activity
    }
}

class Plan {
    .. Attributes ..
    -name : String
    -events : ArrayList<Event>
    --
    .. Constructors ..
    +Plan()
    +Plan(String name, ArrayList<Event> events)
    +Plan(Plan plan)
    .. Methods - Getters ..
    +getName() : String
    +getEvents() : ArrayList<Event>
    .. Methods - Setters ..
    +setName(String name) : void
    +setEvents(ArrayList<Event> events) : void
    .. Methods - Others ..
    +toString() : String
    +equals(Object o) : boolean
    +clone() : Plan
    +addEvent(Event event) : void
    +removeEvent(Event event) : void
    +create(Scanner sc, ArrayList<Activity> userActivities) : Plan
}


class Event {
    .. Attributes ..
    -{static} final MAX_REPETITIONS : int
    -activity : Activity
    -activityRepetitions : int
    -day : int
    -time : LocalTime
    --
    .. Constructors ..
    +Event()
    +Event(Activity activity, int activityRepetitions, int day,
        LocalTime time)
    +Event(Event event)
    .. Methods - Getters ..
    +getMAX_REPETITIONS() : final int
    +getActivity() : Activity
    +getActivityRepetitions() : int
    +getDay() : int
    +getTime() : LocalTime
    .. Methods - Setters ..
    +setActivity(Activity activity) : void
    +setActivityRepetitions(int activityRepetitions) : void
    +setDay(int day) : void
    +setTime(LocalTime time) : void
    .. Methods - Others ..
    +toString() : String
    +equals(Object o) : boolean
    +clone() : Event
    +convertDayToString(int day) : String
    +convertTimeToString(LocalTime time) : String
    +isValidDay(int day) : boolean
    +create(Scanner sc, ArrayList<Activity> userActivities,
        int maxRepetitions int day) : Event
}

class Stats {
    .. Statistics Methods ..
    +mostCaloriesBurned(HashMap<Integer, User> users) : User
    +mostCaloriesBurned(HashMap<Integer, User> users, LocalDate start, LocalDate end) : User
    +mostActivities(HashMap<Integer, User> users) : User
    +mostActivities(HashMap<Integer, User> users, LocalDate start, LocalDate end) : User
    +mostPracticedActivityType(HashMap<Integer, User> users) : String
    +kmTraveled(User user) : double
    +kmTraveled(User user, LocalDate start, LocalDate end) : double
    +altimetryClimbed(User user) : int
    +altimetryClimbed(User user, LocalDate start, LocalDate end) : int
    +mostCaloriesBurnedPlan(HashMap<Integer, User> users) : Plan
    --
    .. Statistics Menu Methods ..
    +displayStatsMenu() : void
    +displayStatsMenu2() : void
    +insertDate(Scanner sc, boolean start) : LocalDate
    +statsMenu(Scanner sc, HashMap<Integer, User> users) : void
}

class Simulation {
    .. Methods ..
    +run(Scanner sc, HashMap<Integer, User> users) : void
    +getSimulationEndDate(Scanner sc, LocalDate startDate) : LocalDate
}

class Main {
    .. Attributes ..
    -updatedState : boolean
    -users : HashMap<Integer, User>
    -defaultStateFilepath : final String 
    --
    .. Methods ..
    +{static} main(String args[]) : void
    -{static} userMenu(Scanner sc, String stateFilepath, Main m, IO io, User user) : void
    -{static} mainMenu(Scanner sc, String stateFilepath, Main m, IO io) : void
    -{static} exit(String stateFilepath, Main m, Scanner sc) : void
    -{static} saveState(String stateFilepath, Main m) : void
    -{static} loadState(String stateFilepath, Main m, Scanner sc) : void
    --
    .. Methods - Manage Users..
    +addUser(User user, int id) : void
    +removeUser(User user) : void
    +updateUser(User user) : void
    --
    ..Methods - Getters..
    +getUpdatedState() : boolean
    +getUsers() : HashMap<Integer, User>
    ..Methods - Setters..
    +setUpdatedState(boolean updatedState) : void
    +setUsers(HashMap<Integer, User> users) : void
}

User <|- User.Type
User "1" *-- "N" Activity
User "1" *-- "1" Plan
Plan "1" *-right- "N" Event
Event "1" *-right- "1" Activity
Main "1" *-- "N" User
Main --> Activity : uses
Main --> Plan : uses
Main --> Stats : uses
Main --> Simulation : uses

@enduml
